Проектная работа к 9-му спринту
badpopoff/java-filmorate pull request #2
Opened 2022-08-27 17:51 UTC by badpopoff

Просьба проверить проектную работу к 9-му спринту.

2022-08-28 08:32 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +@RestController
если аннотации выставлены в порядке увеличения их длины, то такой код проще читать

2022-08-28 08:33 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +    private static final LocalDate FIRST_FILM = LocalDate.of(1895, 12, 28);
лучше назвать `FIRST_FILM_CREATION_DATE`, иначе по названию будет казаться, что переменная хранит фильм

константы стоит отделить пустой строкой от других полей

2022-08-28 08:34 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +    public Collection<Film> findAll (){
нужно сделать автоформатирование кода
ctrl alt L

2022-08-28 08:36 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +            String message = "Такой фильм уже есть в базе!";
в логи стоит добавлять инфу по данным, которые оказались невалидные и тд
тут лучше исправить сообщение и уровень логирования
`log.error("Фильм с id {} уже существует", film.getId());`

2022-08-28 08:37 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +        if(film.getDescription().length() > 200){
200 стоит вынести в константу `MAX_DESCRIPTION_LENGTH`

2022-08-28 09:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/model/Generator.java
> +    private int newId;
нужно разделить пустой строкой

2022-08-28 09:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/model/Generator.java
> +    }
нужно разделить пустой строкой

2022-08-28 09:16 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/model/Generator.java
> +    public void setNewId(int Id) {
переменные пишутся с маленькой буквы

и нужен ли этот метод вообще?

2022-08-28 09:17 UTC, makholin commented on src/test/java/ru/yandex/practicum/fimorate/controller/UserControllerTest.java
> +                , () -> controller.create(checkUser));
нужно добавить автоформатирование кода, запятая должно быть не тут

2022-08-28 09:17 UTC, makholin requested changes
Нужно исправить замечания

2022-08-29 07:24 UTC, badpopoff commented
Поправил код согласно замечаний. Просьба проверить.

2022-08-29 07:28 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/model/Generator.java
> +    private int newId;
Выполнил

2022-08-29 07:28 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/model/Generator.java
> +    public void setNewId(int Id) {
Выполнил. Удалил этот метод.

2022-08-29 07:29 UTC, badpopoff commented on src/test/java/ru/yandex/practicum/fimorate/controller/UserControllerTest.java
> +                , () -> controller.create(checkUser));
Выполнил. Запятые перенёс.

2022-08-29 11:46 UTC, makholin approved these changes
Работа принята

2022-09-03 16:31 UTC, merged