#10 Sprint 10
badpopoff/java-filmorate pull request #3
Opened 2022-09-11 09:31 UTC by badpopoff

2022-09-12 22:24 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/ErrorHandler.java
> +        return new ErrorResponse("Ошибка данных!", e.getMessage());
тут больше похоже не на ошибку данных, а на то, что эти данные не найдены

2022-09-12 22:25 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/ErrorHandler.java
> +    @ExceptionHandler({IllegalArgumentException.class, NullPointerException.class})
NPE - это рантайм исключение, его не нужно обрабатывать таким способом
если оно где-то возникает во время работы приложения, значит в этом месте нужно добавить проверку на null у объекта

2022-09-12 22:27 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +    public List<Film> findPopular(@RequestParam(required = false, defaultValue = "10") String count) {
10 можно вынести в константу `DEFAULT_TOP_LIST_SIZE`

2022-09-12 22:38 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/UserController.java
> +    public User findFilmById(@PathVariable Integer id) {
думаю тут надо findUserById

2022-09-12 22:38 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/UserController.java
> +    public void putFriend(@PathVariable Integer id, @PathVariable Integer friendId) {
метод лучше назвать `addFriend`

2022-09-12 22:41 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/UserController.java
>              String message = "Электронная почта должна содержать символ @.";
в сообщение стоит добавить невалидное значение, чтобы по логам было легче найти проблему

`msg = "Электронная почта должна содержать символ @. Значение: " + user.getEmail();`

2022-09-12 22:42 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/controller/UserController.java
>              String message = "Электронная почта должна содержать символ @.";
для остальных логов с ошибками это тоже актуально

2022-09-12 22:43 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/model/Film.java
> +    private final Set<Integer> idLikeUsers = new HashSet<>();
лучше назвать likedUsers, так будет короче, но все равно понятно, что за список интов  находится в коллекции

2022-09-12 22:46 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/service/FilmService.java
> +                sorted((f0, f1) -> f1.getIdLikeUsers().size() - f0.getIdLikeUsers().size()).
стоит отформатировать код (ctrl alt L в идее)
должно быть так:
```
films = super.findAll()
 .stream()
 .sorted(...)
 .limit(size)
 .collect(...);
```

2022-09-12 22:46 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/service/FilmService.java
> +                sorted((f0, f1) -> f1.getIdLikeUsers().size() - f0.getIdLikeUsers().size()).
можно в переменную films не сохранять, а сразу сделать return super.findAll()....

2022-09-12 22:48 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/service/UserService.java
> +public class UserService extends InMemoryUserStorage {
сервис не должен быть наследником стораджа
это разные слои приложения

в ТЗ сказано
> Сервисы должны быть внедрены в соответствующие контроллеры.

другими словами, каждый слой должен иметь в зависимостях только один более низкий слой:
контроллеры должны работать только с сервисами и не должны ходить в стораджи, это должны делать сервисы

а сервисы у себя в зависимостях уже содержат стораджи

2022-09-12 22:50 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/service/UserService.java
> +public class UserService extends InMemoryUserStorage {
https://bushansirgur.in/java-3-tier-architecture/

2022-09-12 22:57 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/storage/film/FilmStorage.java
> +    Film put(Film film);
непонятно, чем будет отличаться реализация этого метода от createFilm
лучше назвать updateFilm, если в методе идет обновление

2022-09-12 22:58 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
нужен пробел перед {

лучше сразу ко всему коду добавить автоформатирование (ctrl alt L)

2022-09-12 22:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/fimorate/storage/user/InMemoryUserStorage.java
> +    public User put(User user) {
тут тоже стоит назвать updateUser, как и updateFilm

2022-09-12 23:00 UTC, makholin commented on src/test/java/ru/yandex/practicum/fimorate/controller/FilmControllerTest.java
> +
пустая строка перед телом метода не нужна

2022-09-12 23:01 UTC, makholin commented on src/test/java/ru/yandex/practicum/fimorate/controller/FilmControllerTest.java
> +        int idFilm = film.getId();
правильнее такие переменные называть filmId, userId
последнее слово в названии обычно говорит о том, что это за сущность

2022-09-12 23:02 UTC, makholin commented on src/test/java/ru/yandex/practicum/fimorate/controller/UserControllerTest.java
> +                , () -> new UserController(new UserService()).create(user));
UserController и его зависимости лучше создать один раз и сохранить в поле класса-теста

2022-09-12 23:02 UTC, makholin requested changes
Нужно исправить замечания

2022-09-13 05:36 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/controller/ErrorHandler.java
> +        return new ErrorResponse("Ошибка данных!", e.getMessage());
Исправил на return new ErrorResponse("Фильм не найден!", e.getMessage());

2022-09-13 05:37 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/controller/ErrorHandler.java
> +    @ExceptionHandler({IllegalArgumentException.class, NullPointerException.class})
Убрал NPE из обработчика ошибок.

2022-09-13 05:38 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/controller/ErrorHandler.java
> +    @ExceptionHandler({IllegalArgumentException.class, NullPointerException.class})
Получилось как-то так.
@ExceptionHandler
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public ErrorResponse handleIncorrectData(final IllegalArgumentException e) {
        return new ErrorResponse("Ошибка данных!", e.getMessage());
    }

2022-09-13 05:41 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +    public List<Film> findPopular(@RequestParam(required = false, defaultValue = "10") String count) {
Исправил.

2022-09-13 05:47 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/controller/UserController.java
> +    public User findFilmById(@PathVariable Integer id) {
Исправлено!

2022-09-13 06:06 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/controller/UserController.java
> +    public void putFriend(@PathVariable Integer id, @PathVariable Integer friendId) {
Исправлено.

2022-09-13 06:19 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/controller/UserController.java
>              String message = "Электронная почта должна содержать символ @.";
Исправлено.

2022-09-13 06:20 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/model/Film.java
> +    private final Set<Integer> idLikeUsers = new HashSet<>();
Исправлено.

2022-09-13 06:24 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/service/FilmService.java
> +                sorted((f0, f1) -> f1.getIdLikeUsers().size() - f0.getIdLikeUsers().size()).
Исправлено.

2022-09-14 17:55 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/service/UserService.java
> +public class UserService extends InMemoryUserStorage {
Подправил код, как знал. Спасибо за ссылки! С удовольствием почитал статью  https://medium.com/java-vault/layered-architecture-b2f4ebe8d587. Красивый английский!

2022-09-14 18:01 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/storage/film/FilmStorage.java
> +    Film put(Film film);
Исправлено.

2022-09-14 18:02 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
Исправлено.

2022-09-14 18:03 UTC, badpopoff commented on src/main/java/ru/yandex/practicum/fimorate/storage/user/InMemoryUserStorage.java
> +    public User put(User user) {
Исправлено.

2022-09-14 18:13 UTC, badpopoff commented on src/test/java/ru/yandex/practicum/fimorate/controller/FilmControllerTest.java
> +
Исправлено.

2022-09-14 18:18 UTC, badpopoff commented on src/test/java/ru/yandex/practicum/fimorate/controller/FilmControllerTest.java
> +        int idFilm = film.getId();
Исправлено.

2022-09-14 18:59 UTC, badpopoff commented on src/test/java/ru/yandex/practicum/fimorate/controller/UserControllerTest.java
> +                , () -> new UserController(new UserService()).create(user));
Исправлено.

2022-09-15 14:50 UTC, makholin approved these changes
Работа принята

2022-09-15 18:30 UTC, merged